
print("  |  |  |")
print("  |  |  |")
print("  |  |  |")
print("----------")
print("  |  |  |")
print("  |  |  |")
print("  |  |  |")
print("----------")
print("  |  |  | ")
print("  |  |  |")
print("  |  |  |")
print("Example".upper)
print("HOWDY".lower)
print("homework.".count["o"])
print("ball".replace("a", "e"))
print("example".upper[])